### ISSUE TITLE
Support for multi-channel images

### ISSUE THREAD

**Issue by ajertec** [zjniu/Piscis#1]
I see that only single-channel images are supported in your code. Any plans to include multi-channel?

Thank you for your interesting work.

P.S. You might wanna add your paper to the README :)
https://www.biorxiv.org/content/10.1101/2024.01.31.578123v1

**Comment by kvinicki** [comment]
> I see that only single-channel images are supported in your code. Any plans to include multi-channel?
> 
> Thank you for your interesting work.
> 
> P.S. You might wanna add your paper to the README :) https://www.biorxiv.org/content/10.1101/2024.01.31.578123v1

Multi-channel support would be extremely beneficial in reducing the number of false positives. For example, in Fluorescence In Situ Hybridization (FISH), observing the same dot in both FITC and CY3 channels likely indicates a false positive

**Comment by zjniu** [comment]
Thank you for your interest in Piscis! Could you elaborate on what you mean by multi-channel support?

For the example use case that @kvinicki mentioned, I imagine the simplest solution will be to run the model on each channel and then run a postprocessing function to remove duplicate spots across channels. This should be relatively easy to implement, and I am happy to provide such helper functions for convenience.

Are there other multi-channel postprocessing scenarios that you could imagine?

P.S. Thanks, @ajertec, for the suggestion on the README! I will add it soon.

**Comment by ajertec** [comment]
By multi-channel support I mean training/evaluating Piscis model on multi-channel images. To extend the ability of a model to leverage multiple image channels for spot detection. 

Some use-cases:
- Ability to train a model to detect spots that are only inside the nucleus / or some specific region. For example you would provide model with FISH image in the first channel, and image with enhanced / highlighted region in the other channel.
- Ability to help model further distinguish autoflourescent regions from spots of interest (signal). Since flourescent probes have visibility in specific wavelenght regions and autoflourescence is non specific. This could be used for clinical diagnosis of various chromosomal abnormalities, including deletions, duplications, and translocations. See [ref](https://www.nature.com/scitable/topicpage/fluorescence-in-situ-hybridization-fish-327/) Figure 4.

**Comment by kvinicki** [comment]
I've created two GIF animations to better illustrate the nonspecificity of autofluorescence and demonstrate how training on multi-channel images could potentially improve the model's ability to discern true signals more effectively:

![autofluorescence_01](https://github.com/zjniu/Piscis/assets/35938192/3fe8d7c7-9fa3-4dd6-b3ef-44df7f39c56f)
![autofluorescence_02](https://github.com/zjniu/Piscis/assets/35938192/89c59e75-2259-4b92-8719-36cfe39ef021)

**Comment by zjniu** [comment]
I see. Thanks for clarifying and providing additional examples. I had previously considered adding a feature to include an optional “auxiliary” channel, such as the nuclear stain, to help the model better distinguish between true and false positives. This is somewhat similar to the first of the two use cases that @ajertec had mentioned.

However, here are some complications I can see with adding multi-channel support (and why I didn’t rush an implementation for the initial public release of Piscis):

- One of the goals of creating Piscis was to provide a model that can generalize to many scenarios. This can be done with a single-channel model, but when we expand to multi-channel models, the identity of each input channel will need to match how the model was originally trained. This means that it would be virtually impossible to provide a generalized pre-trained model. For example, the two use cases that @ajertec mentioned would require two different models.
- There needs to be a distinction between “primary” channels (where we wish to perform spot detection) and “auxiliary” channels (which we provide only to give the model more information). For example, a nuclear stain would serve as an “auxiliary” channel, as we do not expect the model to return any spots. In the case of preventing autofluorescence, I assume that you would like to detect spots in both the FITC and CY3 channels, in which both are considered “primary” channels. If I were to create an API during model training and evaluation for multi-channel support, this might be confusing and difficult for users to specify. I will need to think more about how to implement this.
- Both use cases could potentially be solved equally or even more robustly with postprocessing and integration with other tools. For example, if you want to detect spots inside nuclear regions, you can first run a segmentation algorithm like Cellpose on the nuclear stain and filter out the spots contained within the resulting nuclear masks. I described a solution for the second use case in my previous reply.

Apologies for a rather long reply. I would like to get your thoughts on the points I made above. If there are cases

**Comment by zjniu** [comment]
I see. Thanks for clarifying and providing additional examples. I had previously considered adding a feature to include an optional “auxiliary” channel, such as the nuclear stain, to help the model better distinguish between true and false positives. This is somewhat similar to the first of the two use cases that @ajertec had mentioned.

However, here are some complications I can see with adding multi-channel support (and why I didn’t rush an implementation for the initial public release of Piscis):

- One of the goals of creating Piscis was to provide a model that can generalize to many scenarios. This can be done with a single-channel model, but when we expand to multi-channel models, the identity of each input channel will need to match how the model was originally trained. This means that it would be virtually impossible to provide a generalized pre-trained model. For example, the two use cases that @ajertec mentioned would require two different models.
- There needs to be a distinction between “primary” channels (where we wish to perform spot detection) and “auxiliary” channels (which we provide only to give the model more information). For example, a nuclear stain would serve as an “auxiliary” channel, as we do not expect the model to return any spots. In the case of preventing autofluorescence, I assume that you would like to detect spots in both the FITC and CY3 channels, in which both are considered “primary” channels. If I were to create an API during model training and evaluation for multi-channel support, this might be confusing and difficult for users to specify. I will need to think more about how to implement this.
- Both use cases could potentially be solved equally or even more robustly with postprocessing and integration with other tools. For example, if you want to detect spots inside nuclear regions, you can first run a segmentation algorithm like Cellpose on the nuclear stain and filter out the spots contained within the resulting nuclear masks. I described a solution for the second use case in my previous reply.

Apologies for a rather long reply. Please let me know your thoughts on the above points, and we will see how we can best move forward!

**Comment by ajertec** [comment]
Thank you for your long response. I appreciate you taking the time.

To address your points:
- Support for multi-channel images might be just that-- only support. It would not hinder the ability to train/provide the single-channel generalized pre-trained model, which could then serve as an initial checkpoint for multi-channel models (initial layer/s in the encoder would need modification to handle extra channels). Training multi-channel models would then be solely user's responsibility.
- I agree, multiple "primary" channels complicate things. One solution is to have single "primary" channel and the model is trained to only detect spots in that channel. For example, model could be trained on both [FITC, CY3, other aux channels, ...] and [CY3, FITC, other aux channels, ...] multi-channel images where both CY3 and FITC are in the first channel but have the other in the second. Its then up to the model to learn the signal / spots based on the combination of properties of FITC-CY3-aux and CY3-FITC-aux. 
- Yes, other tools would be helpful for all use cases. I personally prefer standalone / fusion-based approaches. Model gets much more information and ability to generalize, no need to deal with multiple models (each of which might have its own problems), easier to deploy, etc.

Looking forward to hearing from you.

**Comment by zjniu** [comment]
Thank you for the follow-up! I think your points make sense. The approach of using only a single “primary” channel with the option of providing additional “auxiliary” channels seems to be the most straightforward implementation. As we previously discussed, it will be difficult to provide a generalized multi-channel model. However, it should be relatively easy to partially initialize model weights using those from a pre-trained single-channel model.

I am currently traveling but will be back next week. I hope to start working on this feature then and will follow up if any additional issues arise.

**Comment by kvinicki** [comment]
Hi @zjniu, do you maybe have any updates on this feature?

**Comment by zjniu** [comment]
Hi @ajertec and @kvinicki, please see the linked PR. With this update, Piscis should now be able to train and predict on multichannel images.

When creating a dataset using the [`generate_dataset`](https://github.com/zjniu/Piscis/blob/4693178e4464f84740fd44f19892564e86841288/piscis/data.py#L13) function, make sure that each image in `images` follow the shape convention of (channels, height, width). For example, a 256 x 256 image with 2 channels should have the shape (2, 256, 256). Likewise, when making predictions using a multichannel model, make sure that the input images follow the same axes ordering, namely (batch, z-level [optional], channel [only for multichannel models], height, width).

Please refer to these [notebooks](https://github.com/zjniu/Piscis/tree/main/paper) for examples of dataset creation, model training, and model prediction. Please let me know if you need any help with any issues.

Lastly, note that I have not yet implemented a feature that allows initialization of a new multichannel model using a pre-trained single-channel model. I will continue working on this and push something if this is indeed an effective model training strategy.

**Comment by zjniu** [comment]
Partial initialization of weights for multichannel models using those for single-channel models is now supported by https://github.com/zjniu/Piscis/commit/e6489a08af80311b03372dbc42629980a9b52036, and vice versa. Barring any unforeseen bugs, PR https://github.com/zjniu/Piscis/pull/2 should be ready for your review and subsequent merging.

If you want to test this feature without creating your own datasets, please see https://huggingface.co/datasets/wniu/Piscis/tree/main/20230905/with_dapi. This directory of datasets contains images with two channels: the primary RNA FISH channel and an auxiliary DAPI nuclear channel. During training, set the parameter `dataset_path` to either one of these .npz files or the entire with_dapi directory to load all .npz files.

**Comment by zjniu** [comment]
Hi @ajertec and @kvinicki, have you gotten a chance to test this feature? I will be merging soon unless any issues arise.

**Comment by ajertec** [comment]
Hey, sorry for the late response, it's been a busy week. Thank you so much for this MR :) 
I haven't test it fully, yet, but LGTM.
